### ISSUE TITLE
support AMR-WB format

### ISSUE THREAD

**Issue by belain** [Casstime/amr-duration#1]
support AMR-WB format:

my change of code：

function getDurationByBuffer(buffer, callback) {
  const MAGIC_NUMBER1 = '#!AMR\n';
  const MAGIC_NUMBER2 = '#!AMR-WB\n';
  const PackedByte1 = [12, 13, 15, 17, 19, 20, 26, 31, 5, 0, 0, 0, 0, 0, 0, 0];
  const PackedByte2 = [17, 22, 32, 36, 40, 46, 50, 58, 60, 5, 0, 0, 0, 0, 0, 0];

  let PackedByte = [];
  let MAGIC_NUMBER = '';

  if (buffer.indexOf(MAGIC_NUMBER1) === 0) {
    MAGIC_NUMBER = MAGIC_NUMBER1;
    PackedByte = PackedByte1;
  } else if (buffer.indexOf(MAGIC_NUMBER2) === 0) {
    MAGIC_NUMBER = MAGIC_NUMBER2;
    PackedByte = PackedByte2;
  } else {
    return callback(new Error(`Buffer not start with "${MAGIC_NUMBER}"`));
  }
// the rest is not changed...

**Comment by pansinm** [comment]
代码已修改，npm发布到0.2.0，但是我这边没有AMR-WB的音频，未能进行测试
